import Image from "next/image";
import Link from "next/link";
import { Copy, ExternalLink, Pencil, Plus, Trash2 } from "lucide-react";
import { AdminShell } from "@/components/admin-shell";
import { deleteRecipe, duplicateRecipe } from "./actions";
import { requireAdmin } from "@/lib/auth";
import { db } from "@/lib/db";
import { studioPath } from "@/lib/studio-path";

export const dynamic="force-dynamic";
export default async function Admin(){await requireAdmin();const base=studioPath();const since=new Date(Date.now()-30*86400000);const [recipes,events,subscribers]=await Promise.all([db.recipe.findMany({orderBy:{updatedAt:"desc"}}),db.viewEvent.findMany({where:{createdAt:{gte:since}},select:{recipeId:true,createdAt:true}}),db.newsletterSubscriber.count({where:{active:true}})]);const published=recipes.filter(r=>r.status==="PUBLISHED"&&(!r.publishedAt||r.publishedAt<=new Date())).length;const drafts=recipes.filter(r=>r.status==="DRAFT").length;const scheduled=recipes.filter(r=>r.status==="PUBLISHED"&&r.publishedAt&&r.publishedAt>new Date()).length;const counts=new Map<string,number>();events.forEach(x=>x.recipeId&&counts.set(x.recipeId,(counts.get(x.recipeId)||0)+1));const top=[...recipes].sort((a,b)=>(counts.get(b.id)||0)-(counts.get(a.id)||0)).slice(0,3);return <AdminShell><main className="admin-main"><div className="admin-top"><div><span className="eyebrow">PULSE FOOD STUDIO</span><h1>Bonjour, chef 👋</h1></div><Link className="admin-create" href={`${base}/recettes/nouvelle`}><Plus size={17}/> Nouvelle recette</Link></div><div className="admin-stats"><div className="stat"><span>Recettes publiées</span><b>{published}</b></div><div className="stat"><span>Brouillons</span><b>{drafts}</b></div><div className="stat"><span>Programmées</span><b>{scheduled}</b></div><div className="stat"><span>Vues — 30 jours</span><b>{events.length.toLocaleString("fr-FR")}</b></div><div className="stat"><span>Newsletter</span><b>{subscribers.toLocaleString("fr-FR")}</b></div></div><section className="dashboard-top"><div><span className="eyebrow">TOP RECETTES — 30 JOURS</span>{top.map((r,i)=><p key={r.id}><b>0{i+1}</b><span>{r.title}</span><strong>{counts.get(r.id)||0} vues</strong></p>)}</div><Link href={`${base}/analyses`}>Voir toutes les analyses →</Link></section><section className="admin-table"><div className="table-title"><h2>Toutes les recettes</h2><span>{recipes.length} contenus</span></div>{recipes.map(r=><div className="table-row admin-recipe-row" key={r.id}><div className="thumb"><Image src={r.image} alt="" fill sizes="46px"/></div><b>{r.title}</b><span>{r.category}</span><span>{r.protein}g prot.</span><span className={`status ${r.status.toLowerCase()}`}>{r.publishedAt&&r.publishedAt>new Date()?"Programmée":r.status==="PUBLISHED"?"Publié":r.status==="DRAFT"?"Brouillon":"Archivé"}</span><div className="row-actions"><Link href={`${base}/preview/${r.id}`} target="_blank" title="Prévisualiser"><ExternalLink size={16}/></Link><Link href={`${base}/recettes/${r.id}`} title="Modifier"><Pencil size={16}/></Link><form action={duplicateRecipe.bind(null,r.id)}><button title="Dupliquer"><Copy size={16}/></button></form><form action={deleteRecipe.bind(null,r.id)}><button title="Supprimer"><Trash2 size={16}/></button></form></div></div>)}{!recipes.length&&<div className="admin-empty">Aucune recette. Il est temps de cuisiner.</div>}</section></main></AdminShell>}
