ALTER TABLE "Recipe"
  ADD COLUMN "carbohydrates" INTEGER DEFAULT 0,
  ADD COLUMN "fat" INTEGER DEFAULT 0,
  ADD COLUMN "fiber" INTEGER DEFAULT 0,
  ADD COLUMN "sugar" INTEGER DEFAULT 0,
  ADD COLUMN "sodium" INTEGER DEFAULT 0,
  ADD COLUMN "collections" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];

ALTER TABLE "Ingredient"
  ADD COLUMN "quantity" DOUBLE PRECISION,
  ADD COLUMN "unit" TEXT,
  ADD COLUMN "name" TEXT;
