export type Recipe = { id: string; slug: string; title: string; description: string; image: string; prepMinutes: number; protein: number; calories: number; servings?: number; difficulty: string; category: string; dietary?: string[]; ingredients: string[]; steps: string[]; featured?: boolean };

export const recipes: Recipe[] = [
  { id: "1", slug: "tofu-sesame-crunch", title: "Tofu sésame crunch", description: "Un bowl ultra frais, du tofu doré et une sauce tahini qui lie tout.", image: "/hero-bowl.png", prepMinutes: 25, protein: 34, calories: 520, difficulty: "Facile", category: "Bowl", featured: true, ingredients: ["200 g de tofu ferme", "120 g de riz noir cuit", "100 g d'edamame", "1 avocat", "Broccolini", "Tahini, citron vert, sésame"], steps: ["Presser puis dorer le tofu à feu vif.", "Cuire les broccolini et réchauffer le riz.", "Mélanger tahini, citron vert et un peu d'eau.", "Assembler, ajouter les herbes et servir." ] },
  { id: "2", slug: "gnocchis-cottage-cheese", title: "Gnocchis nuage", description: "Cottage cheese, épinards et citron : le confort, version légère.", image: "https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=1200&q=85", prepMinutes: 20, protein: 29, calories: 460, difficulty: "Rapide", category: "Pasta", ingredients: ["Gnocchis", "Cottage cheese", "Épinards", "Citron"], steps: ["Poêler les gnocchis.", "Ajouter les épinards.", "Lier avec le cottage cheese citronné."] },
  { id: "3", slug: "tacos-haricots-fumes", title: "Tacos smoky beans", description: "Haricots fondants, maïs rôti, pickles minute et crème citronnée.", image: "https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?auto=format&fit=crop&w=1200&q=85", prepMinutes: 18, protein: 26, calories: 490, difficulty: "Facile", category: "Street food", ingredients: ["Haricots rouges", "Tortillas", "Maïs", "Yaourt grec"], steps: ["Épicer et écraser les haricots.", "Griller le maïs.", "Garnir les tortillas."] },
  { id: "4", slug: "shakshuka-verte", title: "Shakshuka verte", description: "Des œufs coulants dans un jardin d'épinards, fèves et herbes.", image: "https://images.unsplash.com/photo-1505253716362-afaea1d3d1af?auto=format&fit=crop&w=1200&q=85", prepMinutes: 30, protein: 31, calories: 430, servings: 2, dietary: ["Sans gluten"], difficulty: "Weekend", category: "Brunch", ingredients: ["4 œufs", "300 g d'épinards", "150 g de fèves", "80 g de feta"], steps: ["Faire tomber les verts.", "Creuser quatre nids.", "Cuire les œufs à couvert."] },
  { id: "5", slug: "dahl-corail-coco", title: "Dahl corail coco", description: "Lentilles corail crémeuses, gingembre frais et citron vert.", image: "https://images.unsplash.com/photo-1585937421612-70a008356fbe?auto=format&fit=crop&w=1200&q=85", prepMinutes: 28, protein: 27, calories: 510, servings: 3, dietary: ["Vegan", "Sans gluten"], difficulty: "Facile", category: "Curry", ingredients: ["300 g de lentilles corail", "400 ml de lait de coco", "2 tomates", "20 g de gingembre", "1 citron vert"], steps: ["Rincer soigneusement les lentilles.", "Faire revenir gingembre et épices.", "Ajouter tomates, coco et lentilles puis mijoter 20 minutes.", "Finir avec le citron vert."] },
  { id: "6", slug: "tempeh-teriyaki", title: "Tempeh teriyaki", description: "Caramélisé, salé, acidulé : le dîner express qui ne manque de rien.", image: "https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1200&q=85", prepMinutes: 22, protein: 36, calories: 540, servings: 2, dietary: ["Vegan"], difficulty: "Rapide", category: "Bowl", ingredients: ["250 g de tempeh", "160 g de riz complet", "200 g de pak choï", "3 c. à soupe de sauce soja", "1 c. à soupe de sirop d'érable"], steps: ["Dorer le tempeh sur toutes ses faces.", "Réduire la sauce soja et le sirop d'érable.", "Sauter le pak choï.", "Assembler avec le riz et napper de sauce."] },
  { id: "7", slug: "pancakes-skyr-citron", title: "Pancakes skyr citron", description: "Épais, moelleux et frais, avec un vrai supplément de protéines.", image: "https://images.unsplash.com/photo-1528207776546-365bb710ee93?auto=format&fit=crop&w=1200&q=85", prepMinutes: 15, protein: 32, calories: 420, servings: 2, dietary: ["Végétarien"], difficulty: "Rapide", category: "Brunch", ingredients: ["200 g de skyr", "2 œufs", "120 g de farine", "1 citron", "1 c. à café de levure"], steps: ["Mélanger le skyr et les œufs.", "Incorporer farine, levure et zestes.", "Cuire les pancakes deux minutes par face."] },
  { id: "8", slug: "salade-croquante-halloumi", title: "Halloumi green crunch", description: "Du croquant, du grillé et une vinaigrette herbacée ultra vive.", image: "https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=1200&q=85", prepMinutes: 20, protein: 30, calories: 480, servings: 2, dietary: ["Sans gluten", "Végétarien"], difficulty: "Facile", category: "Salade", ingredients: ["200 g de halloumi", "150 g de pois chiches", "1 concombre", "150 g de petits pois", "1 bouquet d'herbes"], steps: ["Griller le halloumi.", "Écraser légèrement les pois chiches.", "Tailler les légumes et mixer la vinaigrette.", "Mélanger au dernier moment."] }
];
