import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, Clock3, Flame, Gauge, Zap } from "lucide-react";
import { Logo } from "@/components/icons";
import { AnalyticsBeacon, RecipeExperience } from "@/components/recipe-experience";
import { RecipeCard } from "@/components/recipe-card";
import { getPublishedRecipe, getSimilarRecipes } from "@/lib/recipe-repository";
export const dynamic="force-dynamic";
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const recipe=await getPublishedRecipe(slug);if(!recipe)return{};return{title:`${recipe.title} — PULSE`,description:recipe.description,keywords:[recipe.category,...(recipe.dietary||[]),...(recipe.tags||[])],openGraph:{title:recipe.title,description:recipe.description,type:"article",images:[{url:recipe.image,alt:recipe.title}]},alternates:{canonical:`/recettes/${slug}`}}}
export default async function RecipePage({params}:{params:Promise<{slug:string}>}) {
  const {slug}=await params; const r=await getPublishedRecipe(slug); if(!r)notFound(); const similar=await getSimilarRecipes(r);
  const nutrition={"@type":"NutritionInformation",calories:`${r.calories} kcal`,proteinContent:`${r.protein} g`,carbohydrateContent:`${r.carbohydrates||0} g`,fatContent:`${r.fat||0} g`,fiberContent:`${r.fiber||0} g`,sugarContent:`${r.sugar||0} g`,sodiumContent:`${r.sodium||0} mg`};
  const jsonLd={"@context":"https://schema.org","@type":"Recipe",name:r.title,description:r.description,image:[new URL(r.image,"https://pulsefood.fr").toString()],author:{"@type":"Organization",name:"PULSE Food"},prepTime:`PT${r.prepMinutes}M`,totalTime:`PT${r.prepMinutes}M`,recipeYield:`${r.servings||2} portions`,recipeCategory:r.category,recipeCuisine:"Cuisine végétarienne",keywords:[...(r.tags||[]),...(r.collections||[])].join(", "),recipeIngredient:r.ingredients,recipeInstructions:r.steps.map((text,index)=>({"@type":"HowToStep",position:index+1,text})),nutrition};
  return <main className="detail"><AnalyticsBeacon recipeId={r.id} path={`/recettes/${r.slug}`}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(jsonLd)}}/><header><Link href="/"><Logo/></Link><nav><Link href="/#recettes">Recettes</Link><Link href="/#programme">Collections</Link><Link href="/#manifeste">Manifeste</Link></nav></header><section className="detail-hero"><div className="detail-photo"><Image src={r.image} alt={r.title} fill priority sizes="50vw"/></div><div className="detail-copy"><Link href="/#recettes" className="back"><ArrowLeft size={14}/> Retour aux recettes</Link><div className="dietary-tags">{r.dietary?.map(tag=><span key={tag}>{tag}</span>)}</div><h1>{r.title}</h1><p>{r.description}</p><div className="detail-meta"><span><Clock3 size={17}/>{r.prepMinutes} min</span><span><Gauge size={17}/>{r.difficulty}</span><span><Zap size={17}/>{r.protein}g protéines</span><span><Flame size={17}/>{r.calories} kcal</span></div>{r.collections?.length?<div className="collection-links"><small>Dans les collections</small>{r.collections.map(x=><span key={x}>{x}</span>)}</div>:null}</div></section><RecipeExperience recipe={{id:r.id,slug:r.slug,title:r.title,servings:r.servings||2,ingredients:r.ingredients,structuredIngredients:r.structuredIngredients,steps:r.steps}}/><section className="nutrition"><div><span className="eyebrow">PAR PORTION</span><h2>Repères nutritionnels</h2><p>Valeurs indicatives, calculées pour une portion.</p></div><dl><div><dt>Calories</dt><dd>{r.calories}<small>kcal</small></dd></div><div><dt>Protéines</dt><dd>{r.protein}<small>g</small></dd></div><div><dt>Glucides</dt><dd>{r.carbohydrates||0}<small>g</small></dd></div><div><dt>Lipides</dt><dd>{r.fat||0}<small>g</small></dd></div><div><dt>Fibres</dt><dd>{r.fiber||0}<small>g</small></dd></div><div><dt>Sucres</dt><dd>{r.sugar||0}<small>g</small></dd></div><div><dt>Sodium</dt><dd>{r.sodium||0}<small>mg</small></dd></div></dl></section>{similar.length?<section className="similar"><span className="eyebrow">POURSUIVRE L’INSPIRATION</span><h2>Tu aimeras aussi</h2><div className="recipe-grid">{similar.map((recipe,index)=><RecipeCard key={recipe.id} recipe={recipe} index={index}/>)}</div></section>:null}</main>;
}
